/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DOUBLESIDEDCB
#define DOUBLESIDEDCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class DoubleSidedCB : public RooAbsPdf {
public:
  DoubleSidedCB() {} ; 
  DoubleSidedCB(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _sig,
	      RooAbsReal& _a1,
	      RooAbsReal& _n1,
	      RooAbsReal& _a2,
	      RooAbsReal& _n2);
  DoubleSidedCB(const DoubleSidedCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new DoubleSidedCB(*this,newname); }
  inline virtual ~DoubleSidedCB() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy sig ;
  RooRealProxy a1 ;
  RooRealProxy n1 ;
  RooRealProxy a2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(DoubleSidedCB,1) // Your description goes here...
};
 
#endif