#!/bin/bash

# script for producing pt dependent fiducial cut study plots

function run_file() {
    file=${1}
    outdir=${2}
    pt_bin=$(get_pt ${file})

    mkdir -p ${outdir} # make the base output dir in any case and only get an error when tmp dir already exists
    tmpdir=${outdir}/$(rand_str 32)
    mkdir ${tmpdir}

    plotter=${CHIB_CHIC_POLFW_DIR}/mc_studies/chic_fidcuts_effects.py

    python ${plotter} --outdir ${tmpdir} --extension ${OUTPUTFORMAT} ${file}

    # add pt info to filenames and move them from the temp folder to the output folder
    for f in ${tmpdir}/*ratio.???; do
        mv ${f} $(echo $f | sed "s/ratio\./ratio_pt${pt_bin}\./")
    done
    mv ${tmpdir}/*.??? ${outdir}

    rmdir ${tmpdir} # only remove silently when dir is empty here
}


if [[ $# -lt 1 ]]; then
    echo "Usage: pt_dep_fidcuts OUTDIR [-svg] [INPUT_FILES INPUT_FILES] [-svg]"
fi
if [[ $# -gt 1 ]]; then
    output=${1}
    shift
fi
if $(check_args_flag "-svg" ${@}); then
    echo "Producing svg plots instead of pdf"
    OUTPUTFORMAT="svg"
    shift
else
    OUTPUTFORMAT="pdf"
fi

for file in ${@}; do
    run_file ${file} ${output}
done
