#!/bin/bash

# script for producing pt dependent fiducial cut study plots

function run_file() {
    file1=${3}
    file2=${2}
    outdir=${1}
    pt_bin=$(get_pt ${file1})

    mkdir -p ${outdir} # make the base output dir in any case and only get an error when tmp dir already exists
    tmpdir=${outdir}/$(rand_str 32)
    mkdir ${tmpdir}

    plotter=${CHIB_CHIC_POLFW_DIR}/mc_studies/chic_fidcuts_effects.py

    python ${plotter} --outdir ${tmpdir} --extension ${OUTPUTFORMAT} ${file1} ${file2}

    # add pt info to filenames and move them from the temp folder to the output folder
    for f in ${tmpdir}/*ratio.???; do
        mv ${f} $(echo $f | sed "s/ratio\./ratio_pt${pt_bin}\./")
    done
    mv ${tmpdir}/*.??? ${outdir}

    rmdir ${tmpdir} # only remove silently when dir is empty here
}

function run_dir() {
    base_dir=${1}
    out_dir=${2}
    for pt in {1..5}; do
        pt_files=$(ls ${base_dir}/*__?_pt${pt}.root)
        run_file ${out_dir} ${pt_files}
    done
}


if [[ $# -lt 2 ]]; then
    echo "Usage: pt_dep_fidcuts OUTDIR INPUT_DIR [-svg]"
fi
output=${1}
inbase=${2}
if $(check_args_flag "-svg" ${@}); then
    echo "Producing svg plots instead of pdf"
    OUTPUTFORMAT="svg"
else
    OUTPUTFORMAT="pdf"
fi

run_dir ${inbase} ${output}
